stages:
  - build


build:
  image: node:12.18.4-stretch
  stage: build
  only:
    - tags
  script:
    # Install vuecli
    - npm install -g @vue/cli@latest
    # Install dependencies
    - npm install
    # Build App
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 day

 

